# Generated by Django 5.2.17 on 2026-09-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='shop_reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
