# Generated by Django 5.2.17 on 2026-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('shop', 'Shop'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
