# Generated by Django 5.2.17 on 2026-09-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_register_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('shop', 'Shop'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
